// Generated by CoffeeScript 1.6.3
var AlbumView;

AlbumView = backbone.Model.extend({
  tag: 'li',
  className: 'album',
  initialize: function() {
    _.bindAll(this, 'render');
    this.model.bind('change', this.render);
    return this.template = _.template($('#album-template').html());
  },
  render: function() {
    var renderedContent;
    renderedContent = this.template(this.model.toJSON());
    $(this.el).html(renderedContent);
    return this;
  }
});
